### PR TITLE
feat: add migration 9 to migrate pins to the datastore and back

### PR DESCRIPTION
**Pull request by achingbrain**
Stores pins in the datastore for greatly increased speed of access.

Borrows the pin-set code from js-ipfs to perform the reverse migration.

### CODE REVIEW

**Review by vasco-santos — APPROVED** [review]
Overall looks good to me!
I could not find clear documents on what should be included in the migration, but the code looks good

**Comment by achingbrain** [comment]
@vasco-santos there's more discussion on https://github.com/ipfs/js-ipfs/pull/2771

**Comment by AuHau** [comment]
I would only suggest to add informations about migrations into the Migration matrix, that I can see was not added for the 8th migration as well: https://github.com/ipfs/js-ipfs-repo-migrations#migrations-matrix

**Comment by AuHau** [comment]
And feel free to "kick me out" of the Lead Maintaining of this repo 😉

**Pull request merged**
