### PR TITLE
fix: remove node globals

### PR DESCRIPTION
**Pull request by hugomrdias**
This PR add new datastore for browser and removes node globals.
Also opens datastore in several places!

### CODE REVIEW

**Review by AuHau — APPROVED** [review]
LGTM.

Will the switch to `datastore-idb` need a migration?

**Comment by hugomrdias** [comment]
it shouldn’t, do we have any tests for that ?

**Comment by AuHau** [comment]
Nope, this tool depends on the datastore abstraction and this abstraction is not tested here. 

I am not following `js-ipfs` development lately so not sure what this change is bringing in the bigger scope. If `js-ipfs` moves to this datastore as default one and it uses different storage mechanism, then there should be migration to move the data from the old one to new one 😉

**Comment by hugomrdias** [comment]
backend is the same its just removing one abstraction layer, but still we should keep snapshots to be  able to test this type of stuff

**Comment by AuHau** [comment]
Hmmm I am not really sure what or how to test for this. I mean we can test the abstraction, but I don't think this is the place to do it. 

Do you have a proposal what exactly to test and how?

**Review by achingbrain — APPROVED** [review]

**Review by AuHau — APPROVED** [review]

**Pull request merged**
